rules:
  directConnectToSunnySideWithLogin: #BungeeCode set login is default server
    from: login
    to: sunnyside
    host:
      - play.mcsunnyside.com
      - game.mcsunnyside.com
      - mc.mcsunnyside.com
      - dx.mcsunnyside.com
      - lt.mcsunnyside.com
      - cn.mcsunnyside.com
      - global.mcsunnyside.com
      - fallback.mcsunnyside.com
  directConnectToSunnySideWithoutLogin: #BungeeCode set random server is default server
    from: "#" # '#' = Enter point
    to: sunnyside
    host:
      - direct.mcsunnyside.com
